var fontFamilies = [
    'Arial', 
    'Verdana', 
    'Helvetica', 
    'Times New Roman', 
    'Trebuchet MS', 
    'Georgia', 
    'Garamond', 
    'Courier New', 
    'Brush Script MT', 
    'Lucida Sans Unicode', 
    'Tahoma', 
    'Impact', 
    'Comic Sans MS', 
    'Palatino Linotype', 
    'Arial Black', 
    'Century Gothic', 
    'Lucida Console', 
    'Gill Sans', 
    'Segoe UI', 
    'Calibri', 
    'Optima', 
    'Candara', 
    'Franklin Gothic Medium', 
    'Perpetua', 
    'Bookman', 
    'Baskerville', 
    'Consolas', 
    'Didot', 
    'Copperplate', 
    'Futura'
];

export default fontFamilies